peen/models.py
from werkzeug.security import check_password_hash, generate_password_hash

from peen import db


class Site(db.Model):
    """Sites that can be used."""

    __tablename__ = 'sites'
    id = db.Column(db.Integer, primary_key=True)
    short_name = db.Column(db.String)
    full_name = db.Column(db.String)

    add_site_explanation = db.Column(db.String)
    weight = db.Column(db.Integer)

    def get(self, short_name):
        return self.query.filter_by(short_name=short_name).first()

    def __repr__(self):
        return "Site: id={}, shortname={}, weight={}".format(self.id, self.short_name, self.weight)


class Hacker(db.Model):
    """Metapeen user with all his scores."""

    __tablename__ = 'hackers'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String)
    total_score = db.Column(db.Integer)  # total score with weights

    def __init__(self):
        self.total_score = 0

    def get_site_account(self, short_site_name):
        return self.accounts.filter_by(short_site_name=short_site_name).first()

    def get_score(self, site):
        return self.get_site_account(site).score

    def get_relative_score(self, site):
        score = self.get_site_account(site).get_relative_score()
        return score

    def update_score(self, site, new_score):
        """Update score without weights from site."""
        self.get_site_account(site).update_score(new_score)

    def update_total_score(self):
        """Update total score of all sites with weights."""
        total_score = 0
        for account in self.accounts.all():
            total_score += self.get_relative_score(account.short_site_name)
        self.total_score = int(total_score)
        db.session.commit()

    def add_site_account(self, specific_username, site):
        account = Account(specific_username, site, self)
        self.accounts.append(account)
        db.session.commit()

    def get_optional_sites(self):
        sites = Site.query.all()
        registered_sites = []
        for account in self.accounts:
            registered_sites.append(account.site)
        return [x for x in sites if x not in registered_sites]

    @staticmethod
    def remove_site_account(site_id):
        account = Account.query.get(site_id)
        if account is not None:
            db.session.delete(account)
        db.session.commit()

    def __repr__(self):
        return "Hacker: id='{}', username='{}'".format(self.id, self.username)


class Account(db.Model):
    """Stores info of hacker accounts"""

    def __init__(self, specific_username, site, hacker):
        self.score = 0
        self.specific_username = specific_username

        self.site = site
        self.short_site_name = site.short_name

        self.user = hacker

    __tablename__ = 'accounts'
    id = db.Column(db.Integer, primary_key=True)
    specific_username = db.Column(db.String)
    score = db.Column(db.Integer)

    short_site_name = db.Column(db.String)
    site = db.relationship('Site', backref=db.backref('accounts', lazy='dynamic'))
    site_id = db.Column(db.Integer, db.ForeignKey('sites.id'))

    user = db.relationship('Hacker', backref=db.backref('accounts', lazy='dynamic'))
    user_id = db.Column(db.Integer, db.ForeignKey('hackers.id'))

    def update_score(self, new_score):
        self.score = new_score

    def get_relative_score(self):
        weight = self.site.weight
        return self.score * weight

    def __repr__(self):
        return "Account for {}: username='{}', score='{}'".format(self.short_site_name, self.specific_username, self.score)


class User(db.Model):
    """The admin user"""

    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String)
    password = db.Column(db.String)

    @property
    def is_authenticated(self):
        return True

    @property
    def is_active(self):
        return True

    @property
    def is_anonymous(self):
        return False  # application doesn't support anonymous users

    def get_id(self):
        return self.id

    def set_password(self, new_password):
        self.password = generate_password_hash(new_password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return "User: id='{}', username='{}'".format(self.id, self.username)

peen/__init__.py
#!/usr/bin/env python

""" Handles all the setup for app."""

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from config import configs

db = SQLAlchemy()

lm = LoginManager()
lm.login_view = 'admin.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(configs[config_name])
    configs[config_name].init_app(app)

    db.init_app(app)
    lm.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api/v1.0')

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    return app

peen/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

peen/admin/views.py
from binascii import b2a_hex
from os import urandom
import threading

from flask import request, render_template, redirect, url_for, session, abort
from flask_login import current_user

from peen import db
from peen.models import Hacker, Site
from manage import crawl
from . import admin


def generate_csrf_token():
    if 'token_csrf' not in session:
        session['token_csrf'] = b2a_hex(urandom(15)).decode('utf8')
    return session['token_csrf']


@admin.before_request
def protect_csrf():
    if request.method == 'POST':
        token = session.pop('token_csrf', None)
        if not token or token != request.form.get('token_csrf'):
            abort(403)


@admin.before_request
def check_user():
    if not current_user.is_authenticated:
        abort(401)


@admin.route('/', methods=['GET', 'POST'])
def main():
    """page where you can edit hackers"""
    return render_template('hackers.html',
                           hackers=Hacker.query.all(),
                           token_csrf=generate_csrf_token(),
                           sites=Site.query.all())


@admin.route('/edit_hacker/<int:hacker_id>', methods=['GET', 'POST'])
def edit_hacker(hacker_id):
    return render_template('edit_hacker.html',
                           hacker=Hacker.query.get(hacker_id),
                           token_csrf=generate_csrf_token())


@admin.route('/add_hacker', methods=['POST'])
def add_hacker():
    new_hacker = Hacker()
    new_hacker.username = request.form.get('username')
    db.session.add(new_hacker)
    db.session.commit()

    return redirect(url_for('.main'))


@admin.route('/delete/<int:hacker_id>/', methods=['POST'])
def delete_hacker(hacker_id):
    hacker = Hacker.query.get(hacker_id)
    if hacker is not None:  # if it exists
        db.session.delete(hacker)
        db.session.commit()

    return redirect(url_for('.main'))


@admin.route('/add_site/<int:hacker_id>', methods=['POST'])
def add_site(hacker_id):
    hacker = Hacker.query.get(hacker_id)
    specific_username = request.form.get('specific_username') or hacker.username  # if nothing is provide take normal username
    site = Site.query.filter_by(short_name=request.form.get('site')).first()
    hacker.add_site_account(specific_username, site)

    return redirect(url_for('.edit_hacker', hacker_id=hacker_id))


@admin.route('/delete_site/<int:hacker_id>', methods=['POST'])
def delete_site(hacker_id):
    hacker = Hacker.query.get(hacker_id)
    if hacker is not None:
        hacker.remove_site_account(request.form.get('site'))

    return redirect(url_for('.edit_hacker', hacker_id=hacker_id))


@admin.route('/change_weight', methods=['POST'])
def change_weight():
    site = Site.query.get(request.form.get('site'))
    site.weight = request.form.get('weight')
    db.session.commit()

    return redirect(url_for('.main'))


@admin.route('/crawl_all', methods=['POST'])
def crawl_all():
    crawl_tread = threading.Thread(target=crawl)
    crawl_tread.start()

    return redirect(url_for('.main'))

peen/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import hackers

peen/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

peen/main/views.py
from flask import render_template
from sqlalchemy import desc

from . import main
from peen import lm
from peen.models import User, Hacker


@lm.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@main.route('/')
def index():
    hackers = Hacker.query.order_by(desc(Hacker.total_score)).all()  # get hackers sorted on score
    return render_template('index.html', users=hackers)

peen/templates/forms/add_hacker.html
<h2>Add Hacker: </h2>
<form method="post" name="add_hacker" action="{{ url_for('admin.add_hacker') }}">
    <input name="username" type="text" placeholder="username"><br>
    <input type="submit" value="add hacker">
    <input name="token_csrf" type="hidden" value="{{ token_csrf }}">
</form>

peen/templates/forms/add_site.html
<h2>Add site: </h2>
<form method="post" name="add_site" action="{{ url_for('admin.add_site', hacker_id=hacker.id) }}">
    <label for="site">Site: </label>
    <select name="site" id="site">
        {% for site in hacker.get_optional_sites() %}
            <option value="{{ site.short_name }}">{{ site.add_site_explanation }}</option>
        {% endfor %}
    </select><br>
    <input name="specific_username" type="text" placeholder="specific username"><br> If empty, default to normal username.
    <input type="submit" value="add site">
    <input name="token_csrf" type="hidden" value="{{ token_csrf }}">
</form>

peen/templates/forms/change_weight.html
<h2>Change weight: </h2>
<form method="post" name="change_weight" action="{{ url_for('admin.change_weight') }}">
    <label for="site">Site</label>
    <select name="site" id="site">
    {% for site in sites %}
        <option value="{{ site.id }}">{{ site.full_name }} (current weight: {{ site.weight }})</option>
    {% endfor %}
    </select><br>
    <input name="weight" type="text" placeholder="new weight"><br>
    <input type="submit" value="change weight">
    <input name="token_csrf" type="hidden" value="{{ token_csrf }}">
</form>

peen/templates/forms/crawl_all.html
<h2>Crawl: </h2>
<form method="post" name="crawl_all" action="{{ url_for('admin.crawl_all') }}">
    <input type="submit" value="crawl all sites">
    <input name="token_csrf" type="hidden" value="{{ token_csrf }}">
</form>

peen/templates/forms/delete_hacker.html
<form onsubmit="return confirm('Do you really want to delete the user?');" method="post" name="delete_hacker" action="{{ url_for('admin.delete_hacker', hacker_id=hacker.id) }}">
    <input type="submit" value="delete user">
    <input name="token_csrf" type="hidden" value="{{ token_csrf }}">
</form>

peen/templates/forms/delete_site.html
<h2>Delete site: </h2>
<form method="post" name="delete_site" action="{{ url_for('admin.delete_site', hacker_id=hacker.id) }}">
    <label for="site">Site: </label>
    <select name="site" id="site">
        {% for account in hacker.accounts %}
            <option value="{{ account.id }}">{{ account.site.full_name }}</option>
        {% endfor %}
    </select><br>

    <input type="submit" value="delete site">
    <input name="token_csrf" type="hidden" value="{{ token_csrf }}">
</form>